/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hl7f7IRHWIo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Bookshelf } from "../core/model"
import BooksChart from './books-chart'
import { SearchableBooks } from "./searchable-books"
import Link from "next/link"

export function NewBookshelf({ bookshelf }: { bookshelf: Bookshelf }) {
  return (
    <div className="flex flex-col items-center min-h-screen bg-gray-100 dark:bg-gray-950 dark:text-white">
      <div className="max-w-4xl w-full px-4 md:px-6">
        <div className="flex my-4 lg:my-8 justify-center items-center">
          <BookshelfIcon className="dark:fill-white"/>
          <h1 className="text-3xl mx-4 font-bold">{`My bookshelf`}</h1>
        </div>
        <div className="my-4 lg:my-8 flex flex-col place-items-center">
          <h2 className="text-lg font-light mb-4 text-center">{bookshelf.overview}</h2>
          <Card className="h-full w-full dark:bg-gray-300 dark:text-black">
            <CardHeader>
              <CardTitle>Books read per month</CardTitle>
            </CardHeader>
            <CardContent>
              <BooksChart className="aspect-[9/4] lg:aspect-[9/2]" bookshelf={bookshelf} />
            </CardContent>
          </Card>
        </div>
        <SearchableBooks bookshelf={bookshelf} />
      </div>
      <footer className="w-full mt-12 px-4 md:px-6 py-6 border-t flex justify-between items-center">
        <p className="text-sm text-gray-500 dark:text-gray-400">&copy; {`${new Date().getFullYear()}`} Selçuk Cihan, all rights reserved.</p>
        <Link href="https://github.com/selcukcihan/books" target="_blank" className="text-sm text-gray-500 dark:text-gray-400 hover:underline" prefetch={false}>
          View source code on GitHub
        </Link>
      </footer>
    </div>
  )
}

function BookshelfIcon(props: any) {
  return (
    <svg {...props} width="64" height="64" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><g id="Glyph"><path d="M32,35.002h6v-28H32Zm2-26h2v2H34Zm0,4h2v20H34Z"/><rect x="24" y="9.00195" width="6" height="12"/><polygon points="40 35.002 43.781 35.002 40 16.1 40 35.002"/><polygon points="50.58 29.002 49.38 23.002 43.419 23.002 44.619 29.002 50.58 29.002"/><rect x="24" y="23.00195" width="6" height="6"/><polygon points="46.181 7.002 40.22 7.002 43.02 21.002 48.98 21.002 46.181 7.002"/><rect x="18" y="7.00195" width="4" height="28"/><rect x="8" y="43.00195" width="2" height="14"/><rect x="54" y="43.00195" width="2" height="14"/><rect x="4" y="37.00195" width="56" height="4"/><rect x="14" y="9.00195" width="2" height="26"/><polygon points="51.78 35.002 50.98 31.002 45.019 31.002 45.819 35.002 51.78 35.002"/><rect x="24" y="31.00195" width="6" height="4"/></g></svg>
  )
}
